### ISSUE TITLE
Изменение токена бота и получение ChatID в обработчике сообщений

### ISSUE THREAD

**Issue by szabota** [GyverLibs/FastBot#1]
Очень не хватает функции SetToken, которая отдельно изменяла бы токен бота.

А в функции обработчика входящих сообщений, кроме имени пользователя и текста сообщения хорошо бы получать и ChatID с которого это сообщение пришло.

**Comment by GyverLibs** [comment]
Спасибо за идею, библиотека изначально делалась под свои скромные цели и постепенно обрастает функционалом по заявкам юзеров =)
Выкатил v1.5, добавил смену токена и новый более удобный парсинг сообщений, там chatID, имя и текст

**Comment by szabota** [comment]
Супер!
