### ISSUE TITLE
Не отправляет сообщения когда не уазан CHAT_ID

### ISSUE THREAD

**Issue by Portia-Lin** [GyverLibs/FastBot#10]
Отключил белый лист, указав в коде #define CHAT_ID "", пустую строку. Бот не отправляет сообщения в чат. Если указать свой ид, то бот может отправить мне сообщение. Не понимаю, что я сделал не так

**Comment by GyverLibs** [comment]
Всё так

**Comment by Portia-Lin** [comment]
То есть отправка сообщений возможна только пользователям чат айди которых указан? Хотелось бы иметь возможность отправлять сообщения без указания.
Там конечно есть вариант узнать чат айди пользователя который написал ему и отправить ответ. 
Но мне нужно делать своего рода рассылку всем кто использует бот. Например, у меня проект пожарной сигнализации (курсовая работа) и уведомления должны прийти всем кто общался с ботом. Не записывать же мне чат айди всех кто прислал сообщение в еепром (как вариант)
 Есть другой способ?

**Comment by GyverLibs** [comment]
Если ты отправишь бумажное письмо без указания адреса, куда оно придёт? Здесь аналогично

**Comment by Portia-Lin** [comment]
А зачем тогда написано вставьте пустую строку для отключения проверки? Выглядит не логично, для меня

**Comment by GyverLibs** [comment]
Это "белый список", читай описание к библиотеке. Чтобы игнорировать сообщения от случайных людей, которые могут написать боту
