### ISSUE TITLE
Подвисания если отсутствует связь с интернет.

### ISSUE THREAD

**Issue by phazz1980** [GyverLibs/FastBot#13]
Природа этих подвисаний понятна, но они очень мешают работе контроллера. Можно как-то быстро пинговать наличие выхода в интернет?

**Comment by GyverLibs** [comment]
удалось найти эффективный способ?

**Comment by phazz1980** [comment]
Для esp8266 есть асинхронная библиотека пинга ее использовал. А вот с есп32 ничего не придумал

**Comment by GyverLibs** [comment]
Есть async tcp
https://github.com/me-no-dev/AsyncTCP

**Comment by phazz1980** [comment]
Спасибо, а вообще это к всему боту применить можно? Чтобы вообще не было проблем с подвисаниями?

**Comment by phazz1980** [comment]
https://github.com/cotestatnt/AsyncTelegram2

**Comment by GyverLibs** [comment]
нужно найти асинхронный механизм проверки связи с интернет. Если связи нет - не вызывать `tick()`. Вот эта асинхронная либа для бота написана изначально по другому на низком уровне, наверное можно разобраться и закодить отдельную "затычку" для проверки связи. Странно просто, что нет готовых решений

**Comment by GyverLibs** [comment]
написал свою асинхронную обёртку на класс WiFiClientSecure, так что FastBot скоро переедет на шустрый асинхронный TCP

**Comment by Andr1961** [comment]
Привет, похожая ситуация, если загружен канал wifi у esp,
например музыка+mqtt, то телеграм отваливается,
если в мониторе проверить bot.tickManual(), то возвращает 3,
я так понимаю, далее он http пересоздаёт, но для оживления 
телеграмма, надо после этого что-то принудительно отправить
в телеграмм, после этого он восстанавливается (не надолго(( )

**Comment by Vlakss** [comment]
> Это печально. Я планирую сделать библиотеку асинхронной, но не знаю когда будет на это время. Наработки есть, работа обещает стать очень стабильной и опрос без задержек как раньше

Поясните пожалуйста в каких случаях может подвиснуть (или всё же зависнуть)  esp8266 с этой библиотекой.  Отсутствие wifi, интернета ? Планирую использовать с регулятором температуры, но теперь опасаюсь что может зависнуть и не отработать во время.

**Comment by GyverLibs** [comment]
FastBot2 отлично работает
