### ISSUE TITLE
Ошибка при компиляции

### ISSUE THREAD

**Issue by MalfurionST** [GyverLibs/FastBot#14]
Здравствуйте начиная с версии v2.20 включительно вылетает ошибка 

In file included from E:\arduino\malfurion\MeteoClock-master\firmware\esp\ESP_modul_105_05\ESP_modul_105_05.ino:169:0:
C:\Users\User\Documents\Arduino\libraries\FastBot\src/FastBot.h: In member function 'uint8_t FastBot::update(uint8_t)':
C:\Users\User\Documents\Arduino\libraries\FastBot\src/FastBot.h:771:9: error: 'ESPhttpUpdate' was not declared in this scope
         ESPhttpUpdate.rebootOnUpdate(false);
         ^
exit status 1
Ошибка компиляции для платы LOLIN(WEMOS) D1 R2 & mini.

настройки 
#define FB_NO_OTA
#include <FastBot.h>
FastBot bot(BOT_TOKEN);

ядро ЕСП8266 2.7.4

**Comment by GyverLibs** [comment]
привет, пофикшено
