### ISSUE TITLE
Question: power consumption

### ISSUE THREAD

**Issue by kimstik** [GyverLibs/FastBot#15]
What is mean power consumption of FastBoot ?

**Comment by GyverLibs** [comment]
Library does not consume power, it is software

**Comment by kimstik** [comment]
I mean one of the typical use cases of FastBoot.
Let say https://github.com/GyverLibs/FastBot/blob/main/examples/demo/demo.ino

I wonder how the consumption of ESP32 will differ from ESP8266 one.

some reference: https://www.tablix.org/~avian/blog/archives/2022/08/saving_power_on_an_esp8266_web_server_using_delays/

**Comment by GyverLibs** [comment]
Just compare esp8266 and esp32 consumption

**Comment by kimstik** [comment]
Nice answer for the similar question: 
https://github.com/cnlohr/lolra/issues/2
