### ISSUE TITLE
Бот не читает сообщения в группе.

### ISSUE THREAD

**Issue by Dima744** [GyverLibs/FastBot#18]
Доброго дня!

ну во первых огромное спасибо за уроки и всяческие описания по ардуино и есп

решил попробовать либу......
![Screenshot_20220928-110857](https://user-images.githubusercontent.com/63259046/192726064-6dd2f340-5f8e-41a9-8529-47132e39a981.png)

проблема в том что бот не читает сообщения в группе, читает если только сообщение начинается со слэша "/"
причем в группе у бота написано "has access to messages"

**Comment by GyverLibs** [comment]
Привет, нужно отключить в настройках бота режим Group Privace

**Comment by Dima744** [comment]
Пробовал ставить и в on и в off
[Privacy mode](https://core.telegram.org/bots#privacy-mode) is disabled for dimas_cam_bot [@dimas_cam_bot](https://t.me/dimas_cam_bot).

yfcrjkmrj gjybvf.

![Без имени-1 копия](https://user-images.githubusercontent.com/63259046/192731653-1f10deb8-0d06-41e5-b5f7-6e92b2d9db33.jpg)

**Comment by GyverLibs** [comment]
В таком случае не знаю чем помочь, у всех работает

**Comment by Dima744** [comment]
Спасибо за быстрые ответы, 
после того как бот стал Админом (дал ему права админа в группе)
бот начал читать все сообщения

**Comment by GyverLibs** [comment]
Странно, у меня читает без админки) добавлю в доку
