### ISSUE TITLE
Предложение сделать в виде таска

### ISSUE THREAD

**Issue by SlavaZagaynov** [GyverLibs/FastBot#19]
Если сделать в виде таска, то долгое соединение в случае проблем с интернетом и телегой не будет сказываться на работе loop().

**Comment by GyverLibs** [comment]
Ну, ребята с freertos сами разберутся) а остальных распугивать не стоит

**Comment by SlavaZagaynov** [comment]
но ещё один пример эхо на таске было бы неплохо сделать,  а дальше пусть сами разбираются. просто многие даже не знают с чего начать.

**Comment by GyverLibs** [comment]
сделай пример, я добавлю. Сам не работал с тасками)
