### ISSUE TITLE
Изменение логики парсинга входящих сообщений

### ISSUE THREAD

**Issue by szabota** [GyverLibs/FastBot#2]
"...Если задан ID чата/чатов (через setChatID()) - происходит автоматическое отсеивание сообщений НЕ из указанных чатов..."
Оох! Это есть очень-очень сильное ограничение функционала бота.
На мой взгляд, нужно всегда принимать все сообщения, а обрабатывать их или нет,  уже решать в самом парсере.
А для этого соответственно нужна отдельная функция, которая сверит данный ChatID со списком уже имеющихся в переменной ChatIDs.
И тогда бот будет уже самостоятельно принимать решение, как ему поступать с пришедшим сообщением.
Например, если и правда нужно отсеивать сообщения НЕ из указанных чатов, то это будет запрограммировано как-то примерно так:
if ( !inChatIDs(ID) ) return;

**Comment by GyverLibs** [comment]
В актуальной версии можно не задавать chatID, бот принимает все сообщения и отправляет текст, ID, ID чата и юзернейм. См. доку

**Comment by szabota** [comment]
Дык в том-то и вопрос, что мне нужно и чат ид задавать, и принимать сообщения ещё и из неизвестных чатов.

**Comment by GyverLibs** [comment]
заведи строку-вайтлист chatID, и в парсере отсеивай через .indexOf

**Comment by szabota** [comment]
К примеру, я хочу спрашивать пароль к управлению устройством из чат-бота.
Если пароль совпал, я запоминаю это чат-ид и разрешаю управление.
При этом если другой пользователь пришлёт сообщение, бот у него тоже должен спросить пароль и запомнить новый чат-ид

**Comment by GyverLibs** [comment]
библиотека ничем в этом случае не ограничивает: не задавай внутренний ID список и будешь получать все сообщения и уже сравнивать со своим вайтлистом в любом удобном формате

**Comment by szabota** [comment]
Ладно, тоже вариант.
Спасибо.

**Comment by GyverLibs** [comment]
не, я могу конечно обернуть foo.indexOf(ID), но это уже будет несовместимо с текущей версией, когда установленный ID отсеивает чаты

**Comment by szabota** [comment]
Согласен, внедрять хотелки так, чтобы не разрушить совместимость, это не благодарный труд.
Библиотека получилась супер, спасибо огромное!

**Comment by GyverLibs** [comment]
да незшт, делал под одну задачу, но коллективными хотелками получили отличный аналог тяжеленной telegramBot
