### ISSUE TITLE
Question: How do I change the phrase 'Open Menu'?

### ISSUE THREAD

**Issue by qlalfdu** [GyverLibs/FastBot#22]
Open Menu every time showMenu is sent
How do I change the phrase 'Open Menu'?
thank you!

**Comment by GyverLibs** [comment]
Use `showMenuText(String msg, String menu);`

**Comment by qlalfdu** [comment]
> Use `showMenuText(String msg, String menu);`

Ripple is the speed of light.
Thank you very much.
