### ISSUE TITLE
Broken at 2 byte character after 1 byte character(englash or number )

### ISSUE THREAD

**Issue by qlalfdu** [GyverLibs/FastBot#23]
2byte + 2byte = OK 
ex: 가나

1byte + 2byte = OK 
ex: 1가,  a가

2byte + englash or number = NG 
ex: 가1, 가a

2byte + sign character = OK 
ex: 가@

**Comment by GyverLibs** [comment]
Incoming or outgoing?

**Comment by qlalfdu** [comment]
> Incoming or outgoing?

It happens when I send it to a bot from the desktop.
(laptop > bot)

**Comment by GyverLibs** [comment]
Markdown text mode is off?
Try to
```cpp
#define FB_NO_URLENCODE
```
Before #include fastbot

**Comment by qlalfdu** [comment]
The same goes for changing setTextMode

#define FB_NO_URLENCODE
#include <FastBot.h>
The result is broken.

**Comment by GyverLibs** [comment]
So i don't understand this line
> 2byte + englash or number = NG
ex: 가1, 가a

**Comment by qlalfdu** [comment]
> 

![PN22-910](https://user-images.githubusercontent.com/24924909/204094151-c832e5e2-0f66-4ed0-a948-8e84f55b38f5.png)

**Comment by GyverLibs** [comment]
So 1st and 2nd result is broken?

**Comment by qlalfdu** [comment]
> So 1st and 2nd result is broken?
yes
Breaks down when English or numbers come after Korean

**Comment by GyverLibs** [comment]
Seems like urlencode problem. I think i can fix it

**Comment by GyverLibs** [comment]
By the way, 가 is 3 byte char

**Comment by GyverLibs** [comment]
utils.cpp, line 54, add ` || c > 126`
like this
```cpp
else if (c <= 38 || c == '+' || c > 126) {
```
I will make an update soon and include this fix
