### ISSUE TITLE
Бот А не видит сообщения в группе от бота Б

### ISSUE THREAD

**Issue by Dima744** [GyverLibs/FastBot#28]
Доброго времени суток. Огромное спасибо за Ваш труд.

собственно есть группа. в ней зарегистрированы 2 бота (у каждого бота своя ESP)
собственно проблема, что ни бот А, ни бот Б не видят сообщения в группе
именно сообщения от ботов.....от "живого участника видят"
да и оба бота Админы группы и могут читать сообщения
что подтверждается чтением эхом всех сообщений 
но эхо работает только для людей

**Comment by GyverLibs** [comment]
Привет, согласно API, это невозможно к сожалению
https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots

**Comment by Dima744** [comment]
Мой низкий поклон и спасибо за быстрый ответ.
