### ISSUE TITLE
Bot does not post messages to the chat that contains several topics

### ISSUE THREAD

**Issue by ShaggyDog18** [GyverLibs/FastBot#29]
There is a target chat with several topics. Bot does not accept commands nor post messages to any o the topic including the General one.
I've referenced to the API and in the `sendMessage` method  there is the following in the  [sendMessage API description](https://core.telegram.org/bots/api#sendmessage):
<html>
<body>

message_thread_id | Integer | Optional | Unique identifier for the target message thread (topic) of the forum; for forum supergroups only
-- | -- | -- | --

</body>
</html>

Possible to add `message thread ID ` to the `sendMessage `method of your library?
Thank you!

**Comment by GyverLibs** [comment]
Yes, I can add it, but later

**Comment by ShaggyDog18** [comment]
Thank you! That would be great addition to the existing library.

**Comment by GyverLibs** [comment]
Done in FastBot2 library
