### ISSUE TITLE
Открывать меню без сообщения в чат

### ISSUE THREAD

**Issue by metro-2012** [GyverLibs/FastBot#31]
Привет, большое спасибо за твои крутые библиотеки! 
Заметил, что при вызове функции showMenu, всё равно вызывается функция showMenuText. Подскажи пожалуйста, есть ли возможность открытия меню без отправки сообщения в чат или это ограничения Bot API?

**Comment by GyverLibs** [comment]
Привет, открыть меню без сообщения нельзя, api
