### ISSUE TITLE
Отправка эмодзи

### ISSUE THREAD

**Issue by n0t-amused** [GyverLibs/FastBot#33]
Алекс, привет!

Есть вопрос - как реализовать отправку эмодзи/использование их в названиях пунктов инлайн-меню?
Отправлять юникод, или байты ([отсюда](https://apps.timwhitlock.info/emoji/tables/unicode))?
Нужно ли выбирать какой-нибудь конкретный вид разметки сообщений?

Спасибо заранее!

**Comment by GyverLibs** [comment]
привет, вроде отправляются прямо так `"😋"`

**Comment by GyverLibs** [comment]
Пожалуйста) планируется обновление когда нибудь, будет ещё удобнее и ещё более fast
