### ISSUE TITLE
Возможность доступа к ранее сделанному сообщению в чате по id сообщения.

### ISSUE THREAD

**Issue by wowooshkah** [GyverLibs/FastBot#36]
Возможно ли получить доступ к тексту сообщения по его id?
Если да, то как? 
(Я хочу хранить список авторизованных пользователей в тексте сообщения в чате, куда добавлен бот и считывать его каждый раз при старте бота)

**Comment by GyverLibs** [comment]
Насколько я помню, бот имеет доступ к сообщениям не старше суток. Хранить айдишники лучше в массиве в епром или в файле, для этого айди можно получить в виде int64, в текущей версии библиотеки
