### ISSUE TITLE
Very Fast Bot but Some Issues When Bot In Group

### ISSUE THREAD

**Issue by SebouhArmenakian** [GyverLibs/FastBot#4]
Alex, **very fast boy Thank You Very Much.** 
I am very happy with this library, but I have noticed the following issues when Bot was added in Group.

**These Issues Only When Bot In Group** From Bot not any issue

1) Messages arriving to Bot only through Menu. Other typed messages not reaching to bot.
2) Messages through Menu arriving to Bot as:- Show Menu"},"text":"XYZ where XYZ is the message. Not an issue (msg.text.substring(20) solved this issue.
3) I can't confirm the following issue. According to my friend Bot in Group created on Android Phone and an iOS (iPhone) user in Group, library not working for iPhone user. Sounds strange to me but he used the library for his family (3 Android Phones and 1 iOS (iPhone)).  iPhone user complaining that unable to send messages from Menu. Menu is popping up but not working.

**Anyway, once more time thank you, well done**

**Comment by GyverLibs** [comment]
Fixed in v1.7!
