### ISSUE TITLE
Are there plans to create English documentation ?

### ISSUE THREAD

**Issue by asmaklad** [GyverLibs/FastBot#43]
Are there plans to create English documentation ?
if I ask for support would you answer me in English ?

**Comment by GyverLibs** [comment]
There is a button "english docs" at the top of readme, it leads to https://github-com.translate.goog/GyverLibs/FastBot?_x_tr_sl=ru&_x_tr_tl=en
And yes, i will answer in English if you ask

**Comment by asmaklad** [comment]
Many thanks.
