### ISSUE TITLE
Создание бота-дворецкого 

### ISSUE THREAD

**Issue by plsdemo0** [GyverLibs/FastBot#44]
Здравствуйте, у меня вопрос: возможно ли создать средствами этой библиотеки бота-дворецкого? Бот должен просто приветствовать новых участников, которые только присоединились к группе. Как я понял в API от телеграмма такая функция есть, но как она на практике работает, я не совсем понимаю

**Comment by GyverLibs** [comment]
Привет, в библиотеке нет готового метода для получения событий о присоединении нового участника. В телеграм это есть, бот просто получает сообщение о том что присоединился такой то юзер

**Comment by plsdemo0** [comment]
Можете, пожалуйста, подсказать способ реализации?

**Comment by plsdemo0** [comment]
Можете, пожалуйста, подсказать способ реализации такого способа?

**Comment by GyverLibs** [comment]
Модифицировать эту библиотеку или использовать другую где реализовано всё api или есть возможность вручную json разобрать

**Comment by GyverLibs** [comment]
В новой FastBot2 доступен весь api telegram
