### ISSUE TITLE
ID CHAT

### ISSUE THREAD

**Issue by Dimoschka** [GyverLibs/FastBot#50]
Плохо работает с групповыми чатами, Точнее работает только меню, любые сообщения из группового чата, игнорит, кроме функций меню. В личном чате работает без проблем. Так же все обновления по воздуху только через личный чат, групповой игнорит. Возможно проблема в том что номер группового чата идет с минусом.
И вопрос можно ли в функции bot.sendMessage(temp_data, "ID_CHAT"); заменить ID_CHAT на String?
Пример:
String s("12345612312");                  // Мой номер чата
bot.sendMessage("какие то данные", s);     //Сообщение уходить только в этот чат

Просто удобно отвечать только в тот чат который прислал запрос, а не автоматом во все чаты слать. Будет ли такая конструкция работать стабильно?

**Comment by GyverLibs** [comment]
1. [Тут](https://github.com/GyverLibs/FastBot#%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%B1%D0%BE%D1%82%D0%B0): `Для полноценной работы в группе (супергруппе) бота нужно сделать администратором!`
2. `uint8_t sendMessage(String msg, String id);` - принимает String
