### ISSUE TITLE
Есть ли в библиотеке метод отправки изображений из интернета?

### ISSUE THREAD

**Issue by 40inD** [GyverLibs/FastBot#53]
Есть ли в библиотеке метод отправки изображений из интернета?
Например, как сделано на C# библиотеках: 
`Bot.SendPhoto(int channelId,photo : "http://abc.jpeg",caption:"hii");`
или
`Message[] messages = await botClient.SendMediaGroupAsync(
    chatId: chatId,
    media: new IAlbumInputMedia[]
    {
        new InputMediaPhoto("https://cdn.pixabay.com/photo/2017/06/20/19/22/fuchs-2424369_640.jpg"),
        new InputMediaPhoto("https://cdn.pixabay.com/photo/2017/04/11/21/34/giraffe-2222908_640.jpg"),
    }
);`

**Comment by GyverLibs** [comment]
Получается нету

**Comment by GyverLibs** [comment]
Появилось в FastBot2
