### ISSUE TITLE
Не выводит меню

### ISSUE THREAD

**Issue by pmaster555** [GyverLibs/FastBot#55]
Загрузил из примера тоже не выводит. Что не так может быть?

**Comment by 40inD** [comment]
Попробуйте 
bot.setChatID("");

**Comment by GyverLibs** [comment]
Сообщения приходят, а меню нет?

**Comment by pmaster555** [comment]
> Сообщения приходят, а меню нет?

именно. при чем месяц назад, что-то делал. меню было. а в новом проекте пропало. не понимаю. 

> Попробуйте bot.setChatID("");

оно есть в примере. я же пишу, даже пример не работает.

**Comment by GyverLibs** [comment]
Возможно в телеграмме что то обновилось и сломало отправку меню. Сама библиотека уже давно не обновлялась и дело точно не в ней

**Comment by pmaster555** [comment]
В общем дело вот в чем. У меня во всяком случае

sendMessage?&text=&reply_markup=  - это кусок запроса. если text пустой, меню нет, если туда написать например Start то меню есть

**Comment by GyverLibs** [comment]
всё верно, поэтому в функции есть стандартный текст Show menu. Требование телеграм

**Comment by pmaster555** [comment]
> всё верно, поэтому в функции есть стандартный текст Show menu. Требование телеграм

тогда почему библиотека пытается послать запрос с пустым текстом?

**Comment by pmaster555** [comment]
Скачал библиотеку вручную, заменил, все заработало )
