### ISSUE TITLE
Реализовать получение сообщений от telegram сервера через webhook?

### ISSUE THREAD

**Issue by zzleaderzz** [GyverLibs/FastBot#58]
У телеграмма есть возможность уведомлять бота когда получено новое сообщение. Для этого на стороне бота требуется, на сколько я понимаю, внешний айпи и домен с ssl сертификатом для этого айпи.
Со стороны библиотеки требуется запустить https веб сервер, используя эти сертификаты, чтоб бот мог принимать уведомления от сервера телеграмм.
Ну и регистрацию этого адреса в апи телеграмм командой setWebhook, чтоб тот мог ломиться по этому адресу на нашу ESP с уведомлением о каких-то событиях.

Есть ли в планах реализовать поддержку получения уведомлений через webhook?

**Comment by GyverLibs** [comment]
В планах такого нет
