### ISSUE TITLE
Логгирование и debugmode

### ISSUE THREAD

**Issue by FedorTheUnkle** [GyverLibs/FastBot#60]
Было бы хорошо иметь возможность выводить в Serial логи чтобы ловить проблемы с подключением.
Вчера весь вечер пытался разобраться с ботом и так не смог =( при этом не понятно где именно проблема и в какой момент возникает. (wifi точно подключается и доступ к нему есть).

**Comment by GyverLibs** [comment]
Статус подключения возвращает tick()
