### ISSUE TITLE
Перестал работать

### ISSUE THREAD

**Issue by Hemzy529** [GyverLibs/FastBot#68]
Всё было норм, где-то неделю назад перестало работать в большом проекте. Сделал простой скетч (он ниже), залил на пустую ESP32 - не работает. К wifi подключается, токен и chatid указаны точно правильно (не менял), бота стартанул. Проверял и на домашнем wifi, и раздавая с телефона. Создал ещё одного бота, тоже не работает. Телега поменяла политику по отношению к ботам? Работаю с ESP32 в platformio

```
#include <Arduino.h>
#include <WiFi.h>
#include <ArduinoOTA.h>
#include <FastBot.h>

#define buton 23
#define bot_token "XXXXXXXXXX:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
#define tgid "XXXXXXXXXX"
#define ssid "SSID"
#define pass "password"

FastBot bot(bot_token);

void setup() 
{
  Serial.begin(115200);
  pinMode(buton, INPUT_PULLUP);

  WiFi.begin(ssid, pass);
  while(WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(500);
  }

  ArduinoOTA.begin();

  bot.setChatID(tgid);

  bot.sendMessage("started");
}

void loop() 
{
  ArduinoOTA.handle();
  if (!buton) 
  {
    bot.sendMessage("pressed");
    delay(1000);
  }
}
```

**Comment by GyverLibs** [comment]
Не знаю, вроде в bot api нет новостей. Попробуй FastBot2, сейчас точно работает

**Comment by GyverLibs** [comment]
проверял несколько раз FastBot первой версии, работает исправно

**Comment by Hemzy529** [comment]
так и не понял в чём проблема, у меня всё ещё не работает. с fastbot2 всё норм, так что issue закрываю
