### ISSUE TITLE
Работа библиотеки на нескольких esp

### ISSUE THREAD

**Issue by Mit4el** [GyverLibs/FastBot#69]
Как то можно сделать возможность отправки/обработки сообщений только одной конкретной esp. Или всем esp на которых стоит данная библиотека.
Например сначала отправить запрос кто в сети. И ждать 10 сек.
В библиотеке добавить map, что бы можно было связать/задать имена платам с привязанами chipID
Отправлять сообщение с указанием имени платы
Вопрос один можно ли прочитать сообщение в чате на другой, если оно уже прочитано ботом?

**Comment by WonderCRM** [comment]
Телега не предусматривает работу на одном API KEY нескольких устройств. Точнее работать будет, но сообщение получит то устройство, которое первым проверить наличие новых сообщение.

**Comment by GyverLibs** [comment]
никак, один бот - одна еспшка
