### ISSUE TITLE
Очень не хватает отправки стикеров

### ISSUE THREAD

**Issue by MalfurionST** [GyverLibs/FastBot#7]
Здравствуйте, правда если бы была возможность отправки стикера это было бы очень хорошо..

**Comment by GyverLibs** [comment]
Привет, а в каком виде? Там ведь стикеры находятся в наборах стикеров. Как их просматривать и выбирать?

**Comment by MalfurionST** [comment]
У каждого стикера есть уникальный id например:
CAACAgIAAxkBAAEDyfRh-gxwt3yd7p-sepMGgRrSC0tcrAACxgADUomRIzmUbbF6xf1YIwQ
![Screenshot_2022-04-26-19-19-09-972_org telegram messenger](https://user-images.githubusercontent.com/71415011/165278944-cb53684b-0627-4389-9df3-3f0e92562d54.jpg)

**Comment by MalfurionST** [comment]
Боту шлеш стикер он в ответ его id

**Comment by GyverLibs** [comment]
Крутяк! Протестировал, работает, сегодня добавлю

**Comment by GyverLibs** [comment]
сделал
