### ISSUE TITLE
Как сделать, чтобы бот читал сообщения без слэша?

### ISSUE THREAD

**Issue by tokarto** [GyverLibs/FastBot#72]
Хочу сделать включение света с помощью яндекс алисы. Она отправляет сообщение в группу с ботом для включения, но без слэша, так как она не может отправлять слэш. Подскажите плиз как сделать чтобы бот читал сообщения без слэша?

**Comment by GyverLibs** [comment]
Если он в группе, сделать его админом и отключить приватность

**Comment by tokarto** [comment]
ну 

> Если он в группе, сделать его админом и отключить приватность

ну так бот в группе админ
я в сериал порт в аржуино иде выводил приходящие сообщения, бот просто не видит их(

**Comment by GyverLibs** [comment]
Если бот видит только сообщения со слешем - нужно отключить групповую приватность. Если она отключена после вступления бота в группу - нужно исключить его и добавить заново

**Comment by tokarto** [comment]
> Если бот видит только сообщения со слешем - нужно отключить групповую приватность. Если она отключена после вступления бота в группу - нужно исключить его и добавить заново

Спасибо, оно работает, но есть одно но: сообщение с текстом "lighton" отправленное человеком бот читает, а точно такое же, только отпраленное другим ботом он не читает( 
Как быть, подскажите?

**Comment by GyverLibs** [comment]
Внимательнее читать ридми
