### ISSUE TITLE
А можно поддержать longpolling? 

### ISSUE THREAD

**Issue by vvzvlad** [GyverLibs/FastBot#75]
Насколько я понял, надо просто установить большой таймаут для запроса (секунд 30), и тогда сервер тг будет держать соединение до того момента, пока боту не придет сообщение, т.е. не будет лага между приходом сообщения и очередным опросом сервера.

**Comment by GyverLibs** [comment]
long polling это асинхронная фича и средствами стандартного http client её сделать нельзя. В новой библиотеке FastBot2 реализован такой режим

**Comment by vvzvlad** [comment]
> long polling это асинхронная фича и средствами стандартного http client её сделать нельзя. В новой библиотеке FastBot2 реализован такой режим

А почему нельзя? будет блокировать работу?

**Comment by GyverLibs** [comment]
потому что клиент будет дожидаться ответа сервера, а сервер ничего ему не ответит
