### ISSUE TITLE
Отправка непонятных значений в сериал при tick()

### ISSUE THREAD

**Issue by MalfurionST** [GyverLibs/FastBot#8]
Здравствуйте, начиная с версии 2.6 включительно при сработке tick() шлет непонятные значения в сериал:
11:12:48.600 -> 1743
11:12:54.087 -> 3702
11:12:54.321 -> 261
11:12:57.731 -> 162
11:13:01.281 -> 224
11:13:04.775 -> 205
11:13:08.273 -> 187
11:13:11.819 -> 271
11:13:15.309 -> 255
11:13:18.809 -> 235
если интересно, пишу программу для ESP8266 которая парсит прогноз погоды с openweathermap.org или accuweather.com, курсы валют с сайта Центрабанка или РБК при этом все настройки производятся через общение с ботом (хочу использовать как модуль для Вашей погодной станции, в принципе все работает уже месяц стабильно (сам модуль ESP8266 пока без подключения к погодной станции...)).
и опять в часах хотелось бы часовой пояс в минутах...

**Comment by GyverLibs** [comment]
Опа, мой косяк, забыл убрать вывод отладочный. Спасибо!

С часовым поясом придумаю что нибудь.

**Comment by MalfurionST** [comment]
просто часовой пояс можно получать с openweathermap.org или accuweather.com а там он в минутах и часах...

**Comment by GyverLibs** [comment]
"в минутах и часах" это как? В каком формате передаётся?

**Comment by MalfurionST** [comment]
С опенвезр вообще в секундах, а с аккувезер часы:минуты

**Comment by GyverLibs** [comment]
Я сделал в минутах и часах универсально
