### ISSUE TITLE
inlineMenu

### ISSUE THREAD

**Issue by Andr1961** [GyverLibs/FastBot#9]
Алекс привет, библиотека действительно лёгкая и быстрая, но примеры , где есть inlineMenu (menuTest,menuTest2,query)не смог запустить,
 например menuTest2 начальное меню создаётся, но при нажатии кнопок приходит сообщение меню0  и закрывается, если вручную запустить меню2, то уже не выйти из него , back не работает, на любое нажатие приходить Menu 2
тестировал на wemos d1 mini ver 2.5.2, ide 1.8.16, телеграм последний
PS есть ли в планах EncButton на esp32 с прерыванием? спасибо

**Comment by GyverLibs** [comment]
Привет, esp sdk ставь 2.7.4. Сейчас проверю примеры
EncButton работает на всех платформах, как работать с прерываниями есть в примерах

**Comment by GyverLibs** [comment]
В примере ошибка, в течение часа выпущу релиз, там ещё пару исправлений надо сделать. Спасибо!

**Comment by Andr1961** [comment]
Спасибо за оперативность,
на 2.5.2 у меня самый стабильный wifi,
на старой версии енкодера, сам пробовал прерывание, но что-то не очень получилось, в EncButton по контексту не нашёл IRAM_ATTR, поэтому и спросил про прерывание.   Удачи.

**Comment by GyverLibs** [comment]
как подключать прерывание - надо смотреть в документации к конкретному чипу. У есп надо добавлять атрибуты, на других платформах не надо
